# version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_comercio
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5425:5432"

volumes:
  db-data:
